name: Java CI with Gradle on master Commit

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Mod version'
        required: true
      release_type:
        description: 'Release type (release, beta, alpha)'
        default: 'beta'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Tag Version
        id: tag_version
        run: |
          if [[ ${{ github.ref }} == refs/tags/* ]]; then
            tag=${{ github.ref }}
            tag=${tag/refs\/tags\//}
            tag=${tag//v/}
            tag_message=$(git tag -l --format='%(contents)' "${tag}")
            echo "::set-output name=version::${tag}"
            echo "::set-output name=release_type::${tag_message}"
          elif [[ -n "${{ github.event.inputs.tag_version }}" ]]; then
            echo "::set-output name=version::${{ github.event.inputs.tag_version }}"
            echo "::set-output name=release_type::${{ github.event.inputs.release_type }}"
          fi

      - name: Generate Changelog
        run: |
          echo "## Changelog v${{ steps.tag_version.outputs.version }}-${{ steps.tag_version.outputs.release_type }}" > CHANGELOG.md
          if git describe --tags --abbrev=0 > /dev/null 2>&1; then
            latest_tag=$(git describe --tags --abbrev=0)
            previous_tag=$(git describe --tags --abbrev=0 ${latest_tag}^)
            changelog=$(git log --pretty=format:'- %s' --oneline --decorate --decorate-refs=0 ${previous_tag}..${latest_tag})
            echo "${changelog}" >> CHANGELOG.md
          else
            echo "No tags found" >> CHANGELOG.md
          fi

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish Minecraft Mods
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: 687577
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files-primary: build/libs/!(*-@(dev|sources|javadoc)).jar
          files-secondary: build/libs/*-@(dev|sources|javadoc).jar
          name: GroovyScript-${{ steps.tag_version.outputs.version }}
          version: ${{ steps.tag_version.outputs.version }}
          version-type: ${{ steps.tag_version.outputs.release_type }}
          changelog-file: CHANGELOG.md
          loaders: |
            forge
          game-versions: |
            1.12.2
          dependencies: |
          java: |
            8
          retry-attempts: 2